[carrier]
subcarrier_spacing_khz = 30
cyclic_prefix = "normal"
n_cell_id = 0
n_size_grid = 50
n_start_grid = 0
frame_number = 0
slot_number = 0

[pusch]
waveform = "dft_s_ofdm"
mapping_type = "A"
symbol_allocation = [0, 14]
n_size_bwp = 50
n_start_bwp = 0
mcs_table = 1
mcs_index = 20
dmrs_config_type = 1
dmrs_type_a_position = 2
dmrs_additional_position = 0
dmrs_num_cdm_groups_without_data = 2
dmrs_beta = 1.4125375446227544

[[users]]
name = "ue0"
n_rnti = 1
dmrs_port = 0

[[users]]
name = "ue1"
n_rnti = 2
dmrs_port = 1

[[users]]
name = "ue2"
n_rnti = 3
dmrs_port = 2

[[users]]
name = "ue3"
n_rnti = 4
dmrs_port = 3
